framemd5cmp: check for dependencies

diff --git a/framemd5cmp b/framemd5cmp
--- a/framemd5cmp
+++ b/framemd5cmp
@@ -15,6 +15,8 @@
 NUM_ARGS=2
 SCRIPTNAME=$(basename "${0}")
 VERSION=0.1
+unset dependencies
+dependencies=(ffmpeg ffprobe diff)
 OUTPUT_DIR=.
 
 usage()
@@ -23,7 +25,7 @@ usage()
     echo "Version: framemd5cmp ${VERSION}"
     echo "Usage: framemd5cmp file1 file2"
     echo
-    echo "Dependencies: ffmpeg ffprobe and diff"
+    echo "Dependencies: ${dependencies[@]}"
     echo "Description: This script will evaluate two video files and identify descrepencies between their frames. It will only show where frames between the two files do not decode to exactly equal data."
     echo
     exit
@@ -33,6 +35,31 @@ is_video(){
     # use ffmpeg's index value and stream specifier to determine if the input is a recognized as a video file by ffmpeg
     ffprobe "$1" -show_streams -select_streams v 2> /dev/null | grep "index="
 }
+
+check_dependencies(){
+    deps_ok=YES
+    while [ "$*" != "" ] ; do
+        dependency="$1"
+        if [ ! $(which $dependency) ] ; then
+            echo "This script requires $dependency to run but it is not installed"
+            echo "If you are running ubuntu or debian you might be able to install $dependency with the following command"
+            echo "sudo apt-get install ${dependency}"
+            echo "If you are running mac you might be able to install $dependency with the following command"
+            echo "brew install ${dependency}"
+            deps_ok=NO
+        fi
+        shift
+    done
+    if [[ "$deps_ok" == "NO" ]]; then
+        echo "Unmet dependencies"
+        echo "Aborting!"
+        exit 1
+    else
+    return 0
+    fi
+}
+
+check_dependencies "${dependencies[@]}"
 
 if [ ! "${#}" -eq "${NUM_ARGS}" ] ; then
     echo "Error: ${SCRIPTNAME} requires exactly two inputs."
